language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t ivanlytvynenko/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true ivanlytvynenko/docker-react npm run test
