language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t ivanlytvynenko/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true ivanlytvynenko/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  # can find in s3
  bucket_name: "elasticbeanstalk-us-east-1-736575638857"
  # equals to app name at the beggining
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
